from PyQt5 import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(11, 11, 588, 285))
        self.tabWidget.setObjectName("tabWidget")
        #first tab
        self.tab_add_scores = QtWidgets.QWidget()
        self.tab_add_scores.setObjectName("tab_add_scores")
        self.layout_tab = QtWidgets.QGridLayout(self.tab_add_scores)
        self.layout_tab.setObjectName("layout_tab")
        #username
        self.label_input_username = QtWidgets.QLabel(self.tab_add_scores)
        self.label_input_username.setObjectName("label_input_username")
        self.layout_tab.addWidget(self.label_input_username, 0, 0, 1, 1)
        self.lineedit_input_username = QtWidgets.QLineEdit(self.tab_add_scores)
        self.lineedit_input_username.setObjectName("lineedit_input_username")
        self.layout_tab.addWidget(self.lineedit_input_username, 0, 1, 1, 1)
        #groupbox
        self.groupbox_scores = QtWidgets.QGroupBox(self.tab_add_scores)
        self.groupbox_scores.setObjectName("groupbox_scores")
        self.layout_groupbox_scores = QtWidgets.QFormLayout(self.groupbox_scores)
        self.layout_groupbox_scores.setObjectName("layout_groupbox_scores")
        #add button
        self.toolbutton_add_score = QtWidgets.QToolButton(self.groupbox_scores)
        self.toolbutton_add_score.setObjectName("toolbutton_add_score")
        self.layout_groupbox_scores.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.toolbutton_add_score)
        #add frame for frames
        self.frame_movies_scores = QtWidgets.QFrame(self.groupbox_scores)
        self.frame_movies_scores.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_movies_scores.setObjectName("frame_movies_scores")
        self.layout_frame_movies_scores = QtWidgets.QGridLayout(self.frame_movies_scores)
        self.layout_frame_movies_scores.setObjectName("layout_frame_movies_scores")
        #add widgets to frame
        self.lineedit_input_movie = QtWidgets.QLineEdit(self.frame_movies_scores)
        self.lineedit_input_movie.setObjectName("lineedit_input_movie")
        self.layout_frame_movies_scores.addWidget(self.lineedit_input_movie, 0, 0)
        self.doublespinbox_input_score = QtWidgets.QDoubleSpinBox(self.frame_movies_scores)
        self.doublespinbox_input_score.setObjectName("doublespinbox_input_score")
        self.doublespinbox_input_score.setSingleStep(0.5)
        self.doublespinbox_input_score.setRange(0.5, 5.0)
        self.doublespinbox_input_score.setDecimals(1)
        self.layout_frame_movies_scores.addWidget(self.doublespinbox_input_score, 0, 1)
        self.layout_groupbox_scores.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_movies_scores)
        self.layout_tab.addWidget(self.groupbox_scores, 1, 0, 1, 2)
        self.pushbutton_add_scores = QtWidgets.QPushButton(self.tab_add_scores)
        self.pushbutton_add_scores.setObjectName("pushbutton_add_scores")
        self.layout_tab.addWidget(self.pushbutton_add_scores, 2, 0, 1, 2)
        #second tab
        self.tabWidget.addTab(self.tab_add_scores, "")
        self.tab_get_recommendations = QtWidgets.QWidget()
        self.tab_get_recommendations.setObjectName("tab_get_recommendations")
        self.layout_tab_2 = QtWidgets.QGridLayout(self.tab_get_recommendations)
        self.layout_tab_2.setObjectName("layout_tab_2")
        self.label_input_username_2 = QtWidgets.QLabel(self.tab_get_recommendations)
        self.label_input_username_2.setObjectName("label_input_username_2")
        self.layout_tab_2.addWidget(self.label_input_username_2, 0, 0, 1, 1)
        self.lineedit_input_username_2 = QtWidgets.QLineEdit(self.tab_get_recommendations)
        self.lineedit_input_username_2.setObjectName("lineedit_input_username_2")
        self.layout_tab_2.addWidget(self.lineedit_input_username_2, 0, 1, 1, 1)
        self.spinbox_number_of_recommendations = QtWidgets.QSpinBox(self.tab_get_recommendations)
        self.spinbox_number_of_recommendations.setObjectName("spinbox_number_of_recommendations")
        self.spinbox_number_of_recommendations.setRange(1,100)
        self.layout_tab_2.addWidget(self.spinbox_number_of_recommendations, 0, 2, 1, 1)
        self.pushbutton_get_recommendations = QtWidgets.QPushButton(self.tab_get_recommendations)
        self.pushbutton_get_recommendations.setObjectName("pushbutton_get_recommendations")
        self.layout_tab_2.addWidget(self.pushbutton_get_recommendations, 0, 3, 1, 1)
        self.tablewidget_get_recommendations = QtWidgets.QTableWidget(self.tab_get_recommendations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.tablewidget_get_recommendations.setSizePolicy(sizePolicy)
        self.tablewidget_get_recommendations.setObjectName("tablewidget_get_recommendations")
        self.tablewidget_get_recommendations.setColumnCount(1)
        self.tablewidget_get_recommendations.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_get_recommendations.setHorizontalHeaderItem(0, item)
        self.tablewidget_get_recommendations.horizontalHeader().setStretchLastSection(True)
        self.tablewidget_get_recommendations.setColumnWidth(0, 500)
        self.layout_tab_2.addWidget(self.tablewidget_get_recommendations, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tab_get_recommendations, "")
        Form.setCentralWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Рекомендательная система"))
        self.label_input_username.setText(_translate("Form", "Укажите пользователя"))
        self.groupbox_scores.setTitle(_translate("Form", "Оцените фильмы"))
        self.toolbutton_add_score.setText(_translate("Form", "+"))
        self.pushbutton_add_scores.setText(_translate("Form", "Добавить оценки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_add_scores), _translate("Form", "Добавить оценки"))
        self.label_input_username_2.setText(_translate("Form", "Укажите пользователя"))
        self.pushbutton_get_recommendations.setText(_translate("Form", "Получить рекомендации"))
        item = self.tablewidget_get_recommendations.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название фильма"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_get_recommendations), _translate("Form", "Получить рекомендации"))